export class DatosGenerales {
  constructor(
    public RFC: string,
    public fisica_nombre: string,
    public fisica_apellido_pat: string,
    public fisica_apellido_mat: string,
    public moral_nombre: string,
    public calle: string,
    public num_ext: string,
    public num_int: string,
    public colonia: string,
    public codigo_postal: string,
    public entidad_federativa: string,
    public municipio_alcaldia: string,
    public addcorrespondencia: boolean,
    public correspondencia_calle: string,
    public correspondencia_num_ext: string,
    public correspondencia_num_int: string,
    public correspondencia_colonia: string,
    public correspondencia_codigo_postal: string,
    public correspondencia_entidad_federativa: string,
    public correspondencia_municipio_alcaldia: string,
    
    public lada_telefono:string,
    public telefono:string,
    public lada_celular:string,
    public celular:string,
    public email:string,
    public pagina_web:string,

    public legal_nombre:string,
    public legal_apellido_pat:string,
    public legal_apellido_mat:string,
    public legal_titulo:string,
    public legal_sexo:string,
    public legal_fecha_nacimiento:string,
    public legal_lada_telefono:string,
    public legal_telefono:string,
    public legal_lada_celular:string,
    public legal_celular:string,
    public legal_email:string,
    public director_igual_a_legal: boolean,

    public director_nombre:string,
    public director_apellido_pat:string,
    public director_apellido_mat:string,
    public director_titulo:string,
    public director_sexo:string,
    public director_fecha_nacimiento:string,
    public director_lada_telefono:string,
    public director_telefono:string,
    public director_lada_celular:string,
    public director_celular:string,
    public director_email:string,

    public autoriza_aparezcan_en_directorios: boolean,
    public autoriza_retencion_para_capacitacion: boolean,
    public acepta_aviso_privacidad: boolean
    
  ) //public colonia: string,
  {}
}
